### ISSUE TITLE
Add shared border utilities to Ariakit Tailwind

### ISSUE THREAD

**Issue by diegohaz** [ariakit/ariakit#7466]
## Motivation

Add reusable shared-border behavior to `@ariakit/tailwind` so adjacent surfaces can draw one boundary with the correct tint during hover and selection. Ariakit UI control groups currently implement border overlap and corner rules in their own recipe. The table has a different painting model that keeps shared borders consistent with the active row's surface. The common geometry and painting should be available to Tailwind consumers as well.

This follow-up came from investigating the tab corners introduced during #5240 and the `$joined` option in #7464. It is independent of the tab fix: #7464 can restore independent tab shapes without redesigning shared-border painting.

The existing control-group overlap rules and table painting model are **pre-existing on `main`**, verified at [`a23ef72`](https://github.com/ariakit/ariakit/commit/a23ef727caa80db0769f0329d8d8ccf7c26568e2). The browser evidence below was captured on the #7464 branch at [`2a650a0`](https://github.com/ariakit/ariakit/commit/2a650a08a0c588ae3b2fb91b3c03be799c04a95c). That PR adds an opt-out guard to the control-group rules; it does not change their default border painting, the table recipe, or the Tailwind frame implementation.

### Control groups overlap two borders

[The control-group refinement](https://github.com/ariakit/ariakit/blob/a23ef727caa80db0769f0329d8d8ccf7c26568e2/packages/ariakit-ui/src/styles/control.ts#L417-L441) enables joining for horizontal and stretched layouts with no gap. With `$gap="auto"`, it checks the resolved frame padding through a container style query. It also squares inner corners when the resolved padding is zero.

For two controls with 2px borders, the border overlap is effectively:

```css
.first {
  margin-inline-end: -1px;
}

.next {
  margin-inline-start: -1px;
}
```

This reduces the combined border width, but both borders can still contribute paint. In the `button-group-layout` preview, hover **Week** in the **Horizontal** group. Its right shared border appears darker than its left shared border.

### Cover handles parent-child geometry

[`ak-frame-cover`](https://github.com/ariakit/ariakit/blob/a23ef727caa80db0769f0329d8d8ccf7c26568e2/packages/ariakit-tailwind/src/input.ts#L2444-L2465) stretches a child toward its parent's edges and derives padding and corner geometry from the parent frame. Its [main-axis negative margins apply at the outer edges](https://github.com/ariakit/ariakit/blob/a23ef727caa80db0769f0329d8d8ccf7c26568e2/packages/ariakit-tailwind/src/input.ts#L2274-L2321).

In a horizontal frame, cover alone does not overlap the internal borders between adjacent children. It also changes more geometry than control joining currently does. Replacing the UI refinement with `ak-frame-cover` alone therefore does not preserve the current behavior or solve shared-border tinting.

### The table gives each shared border an owner

[The table uses `border-separate border-spacing-0`](https://github.com/ariakit/ariakit/blob/a23ef727caa80db0769f0329d8d8ccf7c26568e2/packages/ariakit-ui/src/styles/table.ts#L99-L107). It does not depend on native collapsed-border conflict resolution.

- Cells normally draw the border below their row and the divider after their column. The final row and column omit the corresponding outer lines.
- A hovered or selected row also takes the line above it, except where the first-row or sticky-group rules make that unnecessary.
- Its cells paint the row's surface over the preceding row's border, then paint their own translucent edge on top. Later cells can cover earlier cells without adding a state-specific `z-index` to each cell.

For a 1px line above a hovered row, [the two-part shadow](https://github.com/ariakit/ariakit/blob/a23ef727caa80db0769f0329d8d8ccf7c26568e2/packages/ariakit-ui/src/styles/table.ts#L319-L324) reduces to:

```css
box-shadow:
  0 -1px 0 var(--ak-edge),
  0 -1px 0 var(--ak-layer);
```

The first shadow paints on top. The second supplies the correct surface beneath the translucent edge and covers the previous border. Without that surface paint, the old border and the neighboring row's tint can affect the result.

In the inspected light-theme hover state, `--ak-edge` remained a 10% opaque dark color while `--ak-layer` changed. The visible border tint depended on the surface beneath the edge, not just the edge color itself. A browser probe that removed only the surface shadow changed pixels along the line above the hovered row.

The table's `border-image` gradient serves another purpose: it supports inset column dividers. Its sticky-cell and sticky-row-group rules also have specific ownership exceptions. These should inform the design without making the generic utility depend on table markup.

## Reproduction

1. Start the coordinated app servers with `pnpm dev-app` and use the Astro URL printed by that command.
2. Open `/react/previews/button-group-layout/` and hover **Week** in the **Horizontal** group. Compare the left and right shared borders. The [fixture source](https://github.com/ariakit/ariakit/blob/2a650a08a0c588ae3b2fb91b3c03be799c04a95c/app/src/sandbox/button-group-layout/index.react.tsx) sets 2px borders on the controls.
3. Open `/ariakit-ui/table/` and find **Selected rows**. In the first table, hover **Glider**, then **Tabs**, then move the pointer away. Compare the line above each hovered row with its own surface and observe that selected rows retain their tint.

## Browser evidence

The screenshots show the same horizontal group with **Week** hovered. Both captures are 320 × 44 pixels and use 2px control borders.

| Current overlapping borders | Browser prototype with one border per boundary |
| --- | --- |
| ![Week hovered with a darker shared border on its right](https://github.com/user-attachments/assets/75334e4c-6978-44fb-a84d-89571e0a2039) | ![Week hovered with matching shared borders on both sides](https://github.com/user-attachments/assets/71307b3e-6759-4fc2-83af-e40d2d17e2fd) |

In this capture, the left seam was RGB `(211, 212, 212)`, while the right seam was `(190, 191, 191)`. In the prototype, both sampled seams were `(211, 212, 212)`.

The temporary prototype removed the negative inline margins, removed the leading border from controls after the first, and applied this shadow to the hovered middle control:

```css
box-shadow:
  -2px 0 0 var(--ak-edge),
  -2px 0 0 var(--ak-layer);
```

This is a proof of the painting approach for a horizontal LTR group in Chrome. It is not a finished utility or a complete workaround: the probe uses a fixed width, overrides `box-shadow` directly, and does not implement state changes, ring composition, or RTL. No prototype code is committed in #7464.

The following recording shows the existing table's hover behavior across selected and unselected rows:

https://github.com/user-attachments/assets/6979a61a-4997-43bb-9f13-611f32cadf26

## Usage example

The intended UI behavior is an opt-in joined group whose shared borders follow each active control's surface. The UI can retain the `$joined` switch introduced in #7464:

```tsx
<ButtonGroup $joined $p="none" $gap="auto">
  <Button $border={2} $borderType="border">Day</Button>
  <Button $border={2} $borderType="border">Week</Button>
  <Button $border={2} $borderType="border">Month</Button>
</ButtonGroup>
```

Tailwind consumers should be able to express the same behavior without copying the UI recipe's negative-margin selectors or the table's paint formula. A joining utility should compose with `ak-frame-row`, `ak-frame-col`, `ak-frame-cover`, `ak-layer`, and `ak-edge`. Its public name and exact placement on the parent or children are open design decisions.

Hover and selection variants should be able to give an item ownership of adjacent borders. The generic utility should not require Ariakit React components or UI-specific state selectors.

## Requirements

- Draw one visible border per shared boundary. Do not darken a translucent line by painting two edges over it.
- Let an active item paint its own surface beneath a shared edge so the line has the correct tint against that item.
- Support horizontal and vertical flows with logical sides, including RTL.
- Keep joining optional. Independent tabs must retain their own corners when joining is disabled.
- Keep the joining contract distinct from cover's parent-child stretching contract, while allowing the two to compose and share implementation where appropriate.
- Define how joining interacts with group gap, padding, child radius, and declared frame geometry. Preserve the current distinction between a zero gap and zero padding; they do not always imply the same corner treatment.
- Handle equivalent zero-padding values consistently, including `"none"`, `0`, `"0px"`, `"0rem"`, and `"calc(0px)"` in the UI recipe.
- Compose with frame borders, rings, adaptive bordering, existing shadows, and focus indicators. Do not replace the caller's entire `box-shadow` chain.
- Define which item owns a boundary when both adjacent items have a state, including selected/selected and selected/hovered pairs. The current table's paint order is a reference, not a requirement to give hover unconditional priority.
- Define participation and first/last-item handling for hidden items and non-control siblings such as a glider. Wrapped layouts need an explicit support decision rather than treating DOM order as visual adjacency.
- Reuse the common mechanism in the control-group recipe. Evaluate reuse in the table while preserving inset dividers, pinned cells, sticky row groups, outer clipping, and cell/row focus geometry.

## Possible implementation

Extract the reusable concept of a shared border with a defined owner. Separate boundary geometry from the paint that covers a neighboring boundary during a state. Use the resolved `--ak-layer` and `--ak-edge` values for the paint so the existing contextual color system continues to determine the result.

An opt-in frame-joining utility is a candidate. It could share orientation and edge-position calculations with cover, with a variant-compatible way to claim neighboring borders. Do not settle the class names or move the full table recipe into Tailwind before checking both use cases.

The table's one-sided borders plus surface-and-edge shadow are a working starting point. Compare that approach with a border-overlap implementation that explicitly controls paint ownership. Preserving a single painted edge and correct tint is the required outcome; the exact CSS mechanism remains open.

## Validation

Add focused browser coverage for geometry and actual painted pixels. Computed border colors alone will not detect the compositing error demonstrated here.

- Compare shared and unshared edges while hovering the first, middle, and last item in light and dark themes, with high contrast and tinted layers.
- Cover adjacent selected items, hover over a selected item, and different states on neighboring items. Verify the chosen ownership rule without layout movement when the state changes.
- Cover both orientations, RTL, zero and nonzero gaps, padded groups, single items, and the agreed policy for hidden or nonparticipating siblings.
- Check different supported border widths, rings, adaptive bordering, rounded outer corners, shadows, and keyboard focus in Chrome, Firefox, and WebKit.
- If the table adopts the utility, retain its inset-divider, scrolling, pinned-cell, sticky-header/footer, and row/cell focus checks.
- Follow the Tailwind package workflow for rebuilding generated CSS, computed-style snapshots, accessibility checks, and performance validation.

The evidence currently establishes the Chrome LTR border case and the existing table paint model. The full compatibility matrix remains future work.
