### ISSUE TITLE
React lint rules misfire on Solid source

### ISSUE THREAD

**Issue by diegohaz** [ariakit/ariakit#7250]
## Problem

Plain React lint rules run on Solid source and can report defects that do not exist in Solid. This is independent of the React Compiler rules, which [#7248](https://github.com/ariakit/ariakit/pull/7248) scopes away from Solid.

`react/jsx-key` is confirmed. Solid does not need a `key` when rendering a list, but the rule reports one:

```tsx
// packages/ariakit-solid-components/src/example.tsx
export default function Example(props: { items: string[] }) {
  return (
    <ul>
      {props.items.map((item) => (
        <li>{item}</li>
      ))}
    </ul>
  );
}
```

```
example.tsx:4:20: error react(jsx-key): Missing "key" prop for element in iterator.
```

`react/no-children-prop` is suspected for the same reason, since passing `children` as a prop is ordinary in Solid. It has not been confirmed.

## Evidence that this is pre-existing

Reproduced on `main` using the `oxlint.config.ts` from [`65b244f3e`](https://github.com/ariakit/ariakit/commit/65b244f3e11d648c7554f436e6ef3996d9646da7), which declares the `react` plugin at the top level with `categories.correctness: "error"`. `react/jsx-key` is a `correctness` rule, so it has been active on every file, including Solid source, for as long as the plugin has been enabled. This is not introduced by #7248.

## Why this can wait

No committed Solid file triggers it today, so `pnpm lint` is green. Every Solid list in the repository currently uses `<For>` or does not render a list at all. The failure only appears when someone writes `.map()` in Solid source.

## Expected outcome

Decide whether these rules should be disabled for `**/*.solid.*` and `packages/ariakit-solid*/**` alongside the React Compiler rules that #7248 already disables there, or whether Solid should eventually get its own rule set. Confirm whether `react/no-children-prop` misfires as well, and check the remaining `correctness` and `suspicious` React rules against idiomatic Solid rather than adding them one incident at a time.

Discovered during the pre-commit review of #7248.

**Comment by diegohaz** [comment]
Two measurements from the pre-commit review of #7248 that raise the stakes here.

The misfiring set is wider than `react/jsx-key`. On files that import only `solid-js`, these were also observed reporting inside `packages/ariakit-solid*`:

- `react/globals` (error)
- `react/static-components` (error)
- `react/set-state-in-render` (error)
- `react/void-use-memo` (error)
- `react/capitalized-calls` (warning)
- `react/no-unstable-nested-components` (warning)

A minimal reproduction is an idiomatic nested component, which is legal in Solid because a component body runs once:

```tsx
import { createSignal } from "solid-js";

export function Group(props: { label: string }) {
  const Inner = () => <span>{props.label}</span>;
  return <div><Inner /></div>;
}
```

That reports `react(static-components)`, and `react(globals)` as well when the body reads a module-scope variable.

#7248 also sets `options.denyWarnings: true`, so the warning-level entries above now fail CI rather than being advisory. The behavior itself still predates #7248, but the consequence is no longer silent.

**Comment by diegohaz** [comment]
Re-measured against `main` after #7248 merged its fix, since that pull request changed what this issue covers.

#7248 ended up disabling exactly one rule for Solid, `react/immutability`, not the React Compiler set. Every other React rule stays armed on Solid source. So this issue is still open in full, and its surface is slightly larger than when it was filed.

An idiomatic Solid component reports the following under the current configuration. None of it fires on committed Solid code today, so `pnpm lint` is green; all of it fires on ordinary Solid that someone could write tomorrow.

| rule | severity | Solid idiom that triggers it |
| --- | --- | --- |
| `react/refs` | error | `let el!: HTMLDivElement` handed to `ref={el}`, then read in `onMount` |
| `react/purity` | error | `Math.random()` or `Date.now()` in the component body, which runs once |
| `react/static-components` | error | a component declared inside another component |
| `react/jsx-key` | error | `items.map(...)` instead of `<For>` |
| `react/no-children-prop` | error | `children` passed as a prop |
| `react/no-unstable-nested-components` | warning | same nested component as above |

Two notes that change the priority.

`react/refs` is newly armed by #7248; it was off repo-wide before. It misfires on the bare-variable ref form that Solid's own documentation teaches. The repository avoids it today only because `packages/ariakit-solid*` uses the `ref.set` helper from `@ariakit/solid-utils` and the one sandbox uses the callback form, which is the form `react/immutability` covers.

`options.denyWarnings: true`, also added in #7248, means the warning-level row above now fails CI rather than being advisory.

#7248 adopted a deliberately reactive policy, recorded in the config comment: add a rule to the Solid override only once it actually reports. That decision was based on measurements of committed code. The open question for this issue is whether to keep waiting, or to audit the enabled React rules against idiomatic Solid once and disable the ones that cannot apply, before the four Solid packages grow enough to hit them one at a time.
