### PR TITLE
Add shared border utilities to Ariakit Tailwind

### LINKED ISSUE #7466: Add shared border utilities to Ariakit Tailwind
## Motivation

Add reusable shared-border behavior to `@ariakit/tailwind` so adjacent surfaces can draw one boundary with the correct tint during hover and selection. Ariakit UI control groups currently implement border overlap and corner rules in their own recipe. The table has a different painting model that keeps shared borders consistent with the active row's surface. The common geometry and painting should be available to Tailwind consumers as well.

This follow-up came from investigating the tab corners introduced during #5240 and the `$joined` option in #7464. It is independent of the tab fix: #7464 can restore independent tab shapes without redesigning shared-border painting.

The existing control-group overlap rules and table painting model are **pre-existing on `main`**, verified at [`a23ef72`](https://github.com/ariakit/ariakit/commit/a23ef727caa80db0769f0329d8d8ccf7c26568e2). The browser evidence below was captured on the #7464 branch at [`2a650a0`](https://github.com/ariakit/ariakit/commit/2a650a08a0c588ae3b2fb91b3c03be799c04a95c). That PR adds an opt-out guard to the control-group rules; it does not change their default border painting, the table recipe, or the Tailwind frame implementation.

### Control groups overlap two borders

[The control-group refinement](https://github.com/ariakit/ariakit/blob/a23ef727caa80db0769f0329d8d8ccf7c26568e2/packages/ariakit-ui/src/styles/control.ts#L417-L441) enables joining for horizontal and stretched layouts with no gap. With `$gap="auto"`, it checks the resolved frame padding through a container style query. It also squares inner corners when the resolved padding is zero.

For two controls with 2px borders, the border overlap is effectively:

```css
.first {
  margin-inline-end: -1px;
}

.next {
  margin-inline-start: -1px;
}
```

This reduces the combined border width, but both borders can still contribute paint. In the `button-group-layout` preview, hover **Week** in the **Horizontal** group. Its right shared border appears darker than its left shared border.

### Cover handles parent-child geometry

[`ak-frame-cover`](https://github.com/ariakit/ariakit/blob/a23ef727caa80db0769f0329d8d8ccf7c26568e2/packages/ariakit-tailwind/src/input.ts#L2444-L2465) stretches a child toward its parent's edges and derives padding and corner geometry from the parent frame. Its [main-axis negative margins apply at the outer edges](https://github.com/ariakit/ariakit/blob/a23ef727caa80db0769f0329d8d8ccf7c26568e2/packages/ariakit-tailwind/src/input.ts#L2274-L2321).

In a horizontal frame, cover alone does not overlap the internal borders between adjacent children. It also changes more geometry than control joining currently does. Replacing the UI refinement with `ak-frame-cover` alone therefore does not preserve the current behavior or solve shared-border tinting.

### The table gives each shared border an owner

[The table uses `border-separate border-spacing-0`](https://github.com/ariakit/ariakit/blob/a23ef727caa80db0769f0329d8d8ccf7c26568e2/packages/ariakit-ui/src/styles/table.ts#L99-L107). It does not depend on native collapsed-border conflict resolution.

- Cells normally draw the border below their row and the divider after their column. The final row and column omit the corresponding outer lines.
- A hovered or selected row also takes the line above it, except where the first-row or sticky-group rules make that unnecessary.
- Its cells paint the row's surface over the preceding row's border, then paint their own translucent edge on top. Later cells can cover earlier cells without adding a state-specific `z-index` to each cell.

For a 1px line above a hovered row, [the two-part shadow](https://github.com/ariakit/ariakit/blob/a23ef727caa80db0769f0329d8d8ccf7c26568e2/packages/ariakit-ui/src/styles/table.ts#L319-L324) reduces to:

```css
box-shadow:
  0 -1px 0 var(--ak-edge),
  0 -1px 0 var(--ak-layer);
```

The first shadow paints on top. The second supplies the correct surface beneath the translucent edge and covers the previous border. Without that surface paint, the old border and the neighboring row's tint can affect the result.

In the inspected light-theme hover state, `--ak-edge` remained a 10% opaque dark color while `--ak-layer` changed. The visible border tint depended on the surface beneath the edge, not just the edge color itself. A browser probe that removed only the surface shadow changed pixels along the line above the hovered row.

The table's `border-image` gradient serves another purpose: it supports inset column dividers. Its sticky-cell and sticky-row-group rules also have specific ownership exceptions. These should inform the design without making the generic utility depend on table markup.

## Reproduction

1. Start the coordinated app servers with `pnpm dev-app` and use the Astro URL printed by that command.
2. Open `/react/previews/button-group-layout/` and hover **Week** in the **Horizontal** group. Compare the left and right shared borders. The [fixture source](https://github.com/ariakit/ariakit/blob/2a650a08a0c588ae3b2fb91b3c03be799c04a95c/app/src/sandbox/button-group-layout/index.react.tsx) sets 2px borders on the controls.
3. Open `/ariakit-ui/table/` and find **Selected rows**. In the first table, hover **Glider**, then **Tabs**, then move the pointer away. Compare the line above each hovered row with its own surface and observe that selected rows retain their tint.

## Browser evidence

The screenshots show the same horizontal group with **Week** hovered. Both captures are 320 × 44 pixels and use 2px control borders.

| Current overlapping borders | Browser prototype with one border per boundary |
| --- | --- |
| Week hovered with a darker shared border on its right | Week hovered with matching shared borders on both sides |

In this capture, the left seam was RGB `(211, 212, 212)`, while the right seam was `(190, 191, 191)`. In the prototype, both sampled seams were `(211, 212, 212)`.

The temporary prototype removed the negative inline margins, removed the leading border from controls after the first, and applied this shadow to the hovered middle control:

```css
box-shadow:
  -2px 0 0 var(--ak-edge),
  -2px 0 0 var(--ak-layer);
```

This is a proof of the painting approach for a horizontal LTR group in Chrome. It is not a finished utility or a complete workaround: the probe uses a fixed width, overrides `box-shadow` directly, and does not implement state changes, ring composition, or RTL. No prototype code is committed in #7464.

The following recording shows the existing table's hover behavior across selected and unselected rows:

https://github.com/user-attachments/assets/6979a61a-4997-43bb-9f13-611f32cadf26

## Usage example

The intended UI behavior is an opt-in joined group whose shared borders follow each active control's surface. The UI can retain the `$joined` switch introduced in #7464:

```tsx
<ButtonGroup $joined $p="none" $gap="auto">
  <Button $border={2} $borderType="border">Day</Button>
  <Button $border={2} $borderType="border">Week</Button>
  <Button $border={2} $borderType="border">Month</Button>
</ButtonGroup>
```

Tailwind consumers should be able to express the same behavior without copying the UI recipe's negative-margin selectors or the table's paint formula. A joining utility should compose with `ak-frame-row`, `ak-frame-col`, `ak-frame-cover`, `ak-layer`, and `ak-edge`. Its public name and exact placement on the parent or children are open design decisions.

Hover and selection variants should be able to give an item ownership of adjacent borders. The generic utility should not require Ariakit React components or UI-specific state selectors.

## Requirements

- Draw one visible border per shared boundary. Do not darken a translucent line by painting two edges over it.
- Let an active item paint its own surface beneath a shared edge so the line has the correct tint against that item.
- Support horizontal and vertical flows with logical sides, including RTL.
- Keep joining optional. Independent tabs must retain their own corners when joining is disabled.
- Keep the joining contract distinct from cover's parent-child stretching contract, while allowing the two to compose and share implementation where appropriate.
- Define how joining interacts with group gap, padding, child radius, and declared frame geometry. Preserve the current distinction between a zero gap and zero padding; they do not always imply the same corner treatment.
- Handle equivalent zero-padding values consistently, including `"none"`, `0`, `"0px"`, `"0rem"`, and `"calc(0px)"` in the UI recipe.
- Compose with frame borders, rings, adaptive bordering, existing shadows, and focus indicators. Do not replace the caller's entire `box-shadow` chain.
- Define which item owns a boundary when both adjacent items have a state, including selected/selected and selected/hovered pairs. The current table's paint order is a reference, not a requirement to give hover unconditional priority.
- Define participation and first/last-item handling for hidden items and non-control siblings such as a glider. Wrapped layouts need an explicit support decision rather than treating DOM order as visual adjacency.
- Reuse the common mechanism in the control-group recipe. Evaluate reuse in the table while preserving inset dividers, pinned cells, sticky row groups, outer clipping, and cell/row focus geometry.

## Possible implementation

Extract the reusable concept of a shared border with a defined owner. Separate boundary geometry from the paint that covers a neighboring boundary during a state. Use the resolved `--ak-layer` and `--ak-edge` values for the paint so the existing contextual color system continues to determine the result.

An opt-in frame-joining utility is a candidate. It could share orientation and edge-position calculations with cover, with a variant-compatible way to claim neighboring borders. Do not settle the class names or move the full table recipe into Tailwind before checking both use cases.

The table's one-sided borders plus surface-and-edge shadow are a working starting point. Compare that approach with a border-overlap implementation that explicitly controls paint ownership. Preserving a single painted edge and correct tint is the required outcome; the exact CSS mechanism remains open.

## Validation

Add focused browser coverage for geometry and actual painted pixels. Computed border colors alone will not detect the compositing error demonstrated here.

- Compare shared and unshared edges while hovering the first, middle, and last item in light and dark themes, with high contrast and tinted layers.
- Cover adjacent selected items, hover over a selected item, and different states on neighboring items. Verify the chosen ownership rule without layout movement when the state changes.
- Cover both orientations, RTL, zero and nonzero gaps, padded groups, single items, and the agreed policy for hidden or nonparticipating siblings.
- Check different supported border widths, rings, adaptive bordering, rounded outer corners, shadows, and keyboard focus in Chrome, Firefox, and WebKit.
- If the table adopts the utility, retain its inset-divider, scrolling, pinned-cell, sticky-header/footer, and row/cell focus checks.
- Follow the Tailwind package workflow for rebuilding generated CSS, computed-style snapshots, accessibility checks, and performance validation.

The evidence currently establishes the Chrome LTR border case and the existing table paint model. The full compatibility matrix remains future work.

### PR DESCRIPTION
**Pull request by diegohaz**
## Motivation

Adjacent controls currently overlap their translucent borders without covering the paint below. Hovering **Week** in the Horizontal button group leaves a darker shared edge on its right. Tailwind consumers also have to copy the control-group geometry to join their own surfaces.

Fixes #7466.

## Solution

Add `ak-frame-join` on a group, `ak-frame-join-item` on each participating child, and variant-compatible `ak-frame-join-active` to give an item ownership of its neighboring edges. Each item carries its declarations, so the utilities also work through `@apply` in custom CSS classes. Reuse frame orientation and corner context for rows, columns, RTL, and nested covers. Keep the existing overlap geometry and paint an opaque resolved surface beneath each edge. The static item utility prepares joined ring paint; dynamic frame-ring utilities read that value with the existing ring as their fallback, including the adaptive zero-width protection from #7484. Native Tailwind rings, outer shadows, inset shadows, and outlines still compose. Explicit z-index utilities can override active-state stacking.

```tsx
<div className="ak-frame ak-frame-row ak-frame-join flex">
  <button className="ak-layer ak-frame ak-frame-lg/2 ak-frame-border ak-frame-join-item hover:ak-layer-5 hover:ak-frame-join-active">
    Day
  </button>
  <button className="ak-layer ak-frame ak-frame-lg/2 ak-frame-border ak-frame-join-item hover:ak-layer-5 hover:ak-frame-join-active">
    Week
  </button>
</div>
```

The control-group recipe uses these utilities. `$joined={false}` keeps controls independent, and tab lists use that default. Vertical groups can opt in with `$joined`. Auto gaps follow resolved frame padding, so equivalent zero values join consistently. Explicit zero gaps in padded groups keep the inner corner radii.

Active items paint above inactive items. Equal states use DOM paint order, including selected/selected and selected/hovered pairs. The contract covers a single row or column in DOM order with equal declared edge widths and opaque layer colors. Native border joins require the browser's rendered border width to match the declared width. Pixel rounding can break that alignment for fractional widths and at some zoom levels; those combinations are unsupported. Outside frame rings support fractional edges through their declared shadow spread. Hidden items are excluded. `ak-frame-start` and `ak-frame-end` identify the boundaries when decoration siblings are present; the control-group recipe sets these flags for its controls. Joining stays within the immediate parent, so nested independent groups keep their own geometry. Wrapping, reordering, and unequal edge widths are outside this contract. The README documents cover composition, focus priority, and participation.

The table keeps its current implementation. Its one-sided borders, inset border-image dividers, pinned cells, and sticky row groups use different ownership rules. Moving it to overlapping full edges would change that geometry. The shared utility adopts its surface-under-edge painting principle without changing table behavior.

## Preview

Week hovered in the Horizontal group, with matching shared edges:

Week hovered with matching shared borders on both sides

The recording shows hover moving across Day, Week, and Month:

https://github.com/user-attachments/assets/e3867b68-d2e4-4ba9-b202-b5fc7dc7c2a7

## Verification

- `pnpm lint-fix`, `pnpm tsc`, and `pnpm build`.
- Browser geometry and state checks in Chromium, Firefox, and WebKit, including custom classes composed through `@apply`, nested independent groups, border widths, rings, adaptive bordering, selection, RTL, vertical flow, cover, skipped siblings, shadows, theme ring colors, and keyboard focus.
- The visual suite uses 36 existing CI baselines across Chromium, Firefox, and WebKit, down from 702. Middle-item hover captures both shared edges. The focused cases cover custom `@apply` classes, native borders, integer and fractional rings, light/dark themes, contrast, RTL, vertical flow, selection, focus stacking, and control-group integration. The full geometry and stacking matrix remains. All 36 retained screenshots pass in [CI run 34636780406](https://github.com/ariakit/ariakit/actions/runs/34636780406). Both visual jobs passed on the first run and skipped baseline updates. No baselines were regenerated, and no automated screenshot comparison against the old implementation was run.
- Existing Tailwind computed-style snapshots and WCAG checks pass against the updated main baselines. The adaptive-ring regression checks from #7484 also pass.
- The `@apply` fixture fails before the utility fix. The nested-group check also fails while the join setting inherits. Both pass after the fixes.
- A configured default ring color fails when the fallback uses only `currentColor`, and passes with the theme lookup.
- Plain `z-10` and a focus ring with a static `ring-2` width fail before the composition fix and pass afterward.
- The [current performance comparison](https://github.com/ariakit/ariakit/pull/7471#issuecomment-5636488134) covers 27 browser tests and 33 Node benchmarks against `main`, including Tailwind page load and class toggles. All expected jobs, raw round files, and paired payloads were checked. The final report has no significant changes or candidates. An unflagged tab INP decrease lacks repeatability and raw-sample support; it is not an improvement claim.

## Implementation review reassessment

<details>
<summary>Cycle 3: Keep item utilities and reduce paint-slot ownership</summary>

The initial border tint error is visible during ordinary hover and selection. Custom classes, nested groups, native Tailwind focus rings, and explicit focus stacking are common composition cases. Lost focus indicators have a greater impact than the original tint error.

The main assessment and the independent complexity review support the item utility design. It uses the existing frame context and adds no runtime layout state. Keep the overlap and surface-paint mechanism. Move joined ring painting into the existing frame-ring declarations, and let caller z-index utilities override the active-state default. Retain the documented single-flow, equal-width, opaque-layer contract. Wrap detection and table-specific divider or sticky-cell rules remain outside that contract.

This continues the current implementation direction. It does not reset the review-cycle count.

</details>

## Review gate reassessment

<details>
<summary>Cycle 3: Limit native border joining where pixel rounding changes width</summary>

The latest finding is a cosmetic stripe: a declared `0.5px` border can render at `1px`, while the overlap remains `0.5px`. Fractional borders are probably less common than the named widths, but usage frequency is not measured. CSS zoom can also change the rendered width of integer borders. The impact is incorrect width and tint at a shared edge.

The main and independent assessments examined a local width correction. Browser checks ruled out rounding to integer CSS pixels or using device scale alone. The draft `round(line-width, ...)` operation is not supported by the tested Chrome, Firefox, or WebKit versions. A complete correction would require runtime measurements or a larger painting redesign. See the [CSS line-width snapping definition](https://drafts.csswg.org/css-values-4/#round-func).

Keep the static item utility and existing overlap geometry. Narrow the new native-border contract to cases where rendered and declared widths match, and document pixel rounding as a rendering limit. This is a scope change, not a correction of all rounded-border combinations. Fractional outside rings remain supported and have focused geometry and visual coverage. The existing limits for wrapping, reordering, unequal widths, and in-flow nonparticipants remain. Runtime scale handling, platform tables, and table migration would add too much maintenance cost for this cosmetic case.

This material narrowing starts a new review direction. The earlier findings and their dispositions remain part of the audit.

</details>

### CODE REVIEW

File: app/src/sandbox/ariakit-tailwind-7466/style.css [hunk 1]
```diff
@@ -0,0 +1,24 @@
+@import "tailwindcss" source(none);
+@import "@ariakit/tailwind";
+
+@source "./index.react.tsx";
```
[the remark this answers is not in the document]
Comment (diegohaz) [reply app/src/sandbox/ariakit-tailwind-7466/style.css:4]: Are we still using stylelint in this project?

File: app/src/sandbox/ariakit-tailwind-7466/test-browser.ts [hunk 2]
```diff
@@ -0,0 +1,134 @@
...
+          "Vertical ring",
+        ]) {
+          const group = query(q.group(title));
+          await page.mouse.move(0, 0);
+          const idleItem = group.button("Week");
+          await idleItem.scrollIntoViewIfNeeded();
+          const idlePixels = await edgePixels(page, idleItem);
+          expectSameColor(idlePixels.left, idlePixels.top);
+          expectSameColor(idlePixels.right, idlePixels.top);
+          expectSameColor(idlePixels.bottom, idlePixels.top);
```
[the remark this answers is not in the document]
Comment (diegohaz) [reply app/src/sandbox/ariakit-tailwind-7466/test-browser.ts]: Superseded by [`989e6c2`](https://github.com/ariakit/ariakit/commit/989e6c2d2a532e9d976338bf9ebca63ca8523f0f): `frame-pixels.ts` and the same-item color comparisons were removed. The tests now use `visual({ element: q.group(title), ... })` to compare the whole group, including adjacent edges in RTL and vertical cases. The retained baselines pass in Chromium, Firefox, and WebKit in [CI](https://github.com/ariakit/ariakit/actions/runs/34636780406).

Existing CI baseline with Week hovered in the RTL group:

Week hovered in an RTL group, with both adjacent edges visible

File: app/src/sandbox/button-group-layout/test-browser.ts [hunk 3]
```diff
@@ -54,4 +55,54 @@ withFramework(import.meta.dirname, async ({ test, query }) => {
...
+            return Math.max(
+              ...pixels.left.map((channel, index) =>
+                Math.abs(channel - (pixels.right[index] ?? 0)),
+              ),
+            );
+          })
+          .toBeLessThanOrEqual(2);
+        const pixels = await edgePixels(page, item);
+        expectSameColor(pixels.left, pixels.right);
+        expectSameColor(pixels.top, pixels.bottom);
```
[the remark this answers is not in the document]
Comment (diegohaz) [reply app/src/sandbox/button-group-layout/test-browser.ts]: Superseded by [`989e6c2`](https://github.com/ariakit/ariakit/commit/989e6c2d2a532e9d976338bf9ebca63ca8523f0f): the custom `edgePixels` poll was removed. Horizontal and Joined vertical now use the shared `visual()` harness, which waits for fonts and stable crop geometry, then calls `toHaveScreenshot` for the whole group. The vertical case passes in Chromium, Firefox, and WebKit in [CI](https://github.com/ariakit/ariakit/actions/runs/34636780406).

Existing CI baseline with Week hovered in Joined vertical:

Week hovered in Joined vertical, with its top and bottom shared edges visible

**Comment by diegohaz** [comment]
**Obsolete**

- [`989e6c2`](https://github.com/ariakit/ariakit/commit/989e6c2d2a532e9d976338bf9ebca63ca8523f0f) ([reply](https://github.com/ariakit/ariakit/pull/7471#discussion_r3992601173)): Replaced same-item pixel comparisons with whole-group `visual()` comparisons, including RTL and vertical shared edges.
- [`989e6c2`](https://github.com/ariakit/ariakit/commit/989e6c2d2a532e9d976338bf9ebca63ca8523f0f) ([reply](https://github.com/ariakit/ariakit/pull/7471#discussion_r3992607574)): Removed the custom edge-color poll. Horizontal and vertical control groups use the shared screenshot harness.

Both replies include existing CI screenshots. The current visual checks pass in Chromium, Firefox, and WebKit. No new code changes were needed.
